name: Simple Bug Report
description: Quickly report a bug
labels: bug
body:
  - type: input
    id: title
    attributes:
      label: Bug Title
      description: Brief summary of the bug
      placeholder: e.g. App crashes on launch
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Describe the issue
      placeholder: Steps to reproduce, expected behavior, etc.
    validations:
      required: true
